# action.yml
name: 'Migrate'
author: 'Vladimir Pavlov'
description: 'Greet someone and record the time'
inputs:
  migrations-folder:
    description: 'Migrations folder'
    required: true
    default: './migrations'
  database:
    description: 'Connect to database string'
    required: true
  verbose:
    description: 'Show verbose logs'
    default: 'false'
  command:
    description: 'Command to run'
    default: 'up'
runs:
  using: 'docker'
  image: 'Dockerfile'

branding:
  icon: 'database'
  color: 'blue'