# action.yml
name: 'Migrate database'
author: 'Vladimir Pavlov'
description: 'Database seed tool built with golang-migrate'
inputs:
  path:
  command:
    description: 'Command to run'
    required: true
'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.command }}

branding:
  icon: 'database'
  color: 'blue'
