# action.yml
name: 'Migrate'
author: 'Vladimir Pavlov'
description: 'Greet someone and record the time'
inputs:
  migrations-folder:
    description: 'Migrations folder'
    required: false
    default: './migrations'
  command:
    description: 'Command'
    required: false
    default: 'up'
  database:
    description: 'Database connection string'
    required: true
  verbose:
    description: 'Enable verbose logging'
    default: 'false'
runs:
  using: 'docker'
  image: 'migrate/migrate'
  args:
    - -path 
    - ${{ inputs.migrations-folder }}
    - -database 
    - ${{ inputs.database }}
    - -verbose
    - ${{ inputs.verbose }}
    -  ${{ inputs.command }}

branding:
  icon: 'database'
  color: 'blue'