# action.yml
name: 'Migrate database'
author: 'Vladimir Pavlov'
description: 'Database seed tool built with golang-migrate'
inputs:
  command:
    description: 'Command to run'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'

branding:
  icon: 'database'
  color: 'blue'
