# action.yml
name: 'Migrate'
author: 'Vladimir Pavlov'
description: 'Greet someone and record the time'
inputs:
  path:
    description: 'Migrations folder'
    required: true
    default: './migrations'
  database:
    description: 'Connect to database string'
    required: true
  verbose:
    description: 'Show verbose logs'
    default: ''
  command:
    description: 'Command to run'
    default: 'up'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args: 
    - ${{ inputs.path }}
    - ${{ inputs.database }}
    - ${{ inputs.verbose }}
    - ${{ inputs.command }}

branding:
  icon: 'database'
  color: 'blue'