# action.yml
name: 'Migrate'
author: 'Vladimir Pavlov'
description: 'Greet someone and record the time'
inputs:
  migrations-folder:
    description: 'Migrations folder'
    required: true
    default: './migrations'
  database:
    description: 'Connect to database string'
    required: true
runs:
  using: 'docker'
  image: 'migrate/migrate'
  args:
    - -path 
    - ${{ inputs.migrations-folder }}
    - -database 
    - ${{ inputs.database }}
    - up 2

branding:
  icon: 'database'
  color: 'blue'