on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:  
      - name: Checkout
        uses: actions/checkout@v3
      - uses: harmon758/postgresql-action@v1
        with:
          postgresql version: '15'
          postgresql db: 'database'
      - uses: ./
        with:
          migrations-folder: ./migrations
          database: postgres://localhost:5432/database up 2