on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:  
      - name: Checkout
        uses: actions/checkout@v2
      - uses: ./action.yml
        with:
          migrations-folder: ./migrations
          database: postgres://localhost:5432/database up 2