on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test migrate up with postgres
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: secret
          POSTGRES_DB: database
        ports:
          - 6666:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:  
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check with version flag
        uses: ./
        with:
          command: '-path ./migrations -database postgresql://postgres:secret@localhost:6666/database?sslmode=disable -verbose up'